version: "3.7"

services:
  database_api-fav-blogs:
    image: postgres
    container_name: database_api-fav-blogs
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${ORM_USERNAME}
      - POSTGRES_PASSWORD=${ORM_PASSWORD}
      - POSTGRES_DB=${ORM_DATABASE}
    volumes:
    - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: api-fav-blogs
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    network_mode: host


volumes:
  pgdata:
    driver: local   